# Generated by Django 5.2.8 on 2025-12-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_reallyuser_biography_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарии к посту'),
        ),
    ]
