# Generated by Django 5.2.8 on 2025-12-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарии к посту'),
        ),
    ]
