# Generated by Django 5.2.8 on 2025-12-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reallyuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/image.png', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
